version: 0.2

env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"
  secrets-manager:
     GIT_USERNAME: SF-SDN-GIT-TOKEN:GIT_USERNAME
     GIT_PASSWORD: SF-SDN-GIT-TOKEN:GIT_PASSWORD
     # key: secret-id:json-key:version-stage:version-id
  #exported-variables:
     # - variable
     # - variable
  #git-credential-helper: yes

phases:
  install:
    #If you use the Ubuntu standard image 2.0 or later, you must specify runtime-versions.
    #If you specify runtime-versions and use an image other than Ubuntu standard image 2.0, the build fails.
    runtime-versions:
        python: 3.8
    #commands:
      # - command
      # - command
  pre_build:
    commands:
        - curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get > get_helm.sh
        - chmod +x get_helm.sh
        - ./get_helm.sh
        - helm version
        - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.15.10/2020-02-22/bin/darwin/amd64/kubectl
        - chmod +x ./kubectl
        - mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
        - kubectl version --short --client
  build:
    commands:
        - echo $GIT_USERNAME
        - echo $GIT_PASSWORD
        - echo $MANIFEST_FILE
        - pwd
        - ls -lrt
        - cd ..
        - git clone https://$GIT_USERNAME:$GIT_PASSWORD@github.com/sf-sdn/cni-deployer.git cni-deployer
        - cd cni-deployer
        - ls
        - mkdir -p Manifests/Output/
        - make setup
        #- make test
        - ls -lrt Manifests/Output/
        - make template
        - ls -lrt Manifests/Output/
        - cd ..
        - rm -rf cni-deployer
  #post_build:
    #commands:
      # - command
      # - command
#reports:
  #report-name-or-arn:
    #files:
      # - location
      # - location
    #base-directory: location
    #discard-paths: yes
    #file-format: JunitXml | CucumberJson
#artifacts:
  #files:
    # - location
    # - location
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths
